name: 'pylint3-action'
description: 'Perform Style Checking on your Python 3 code base using pycodestyle'
branding:
  icon: 'award'  
  color: 'blue'
inputs:
  filename:  
    description: 'filename'
    required: true
    default: 'test.py'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filename }}
